import type { Metadata } from 'next'
import './styles/globals.scss'
import { barlow, barlowCondensed, bellefair } from './utils/fonts'

export const metadata: Metadata = {
  title: 'Space travel website',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowCondensed} ${bellefair} ${barlow}`}
      >
        {children}
      </body>
    </html>
  )
}
